# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 5 sdk'
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: DotNetCoreCLI@2
  displayName: 'Publish Harvest.Web'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    projects: './Harest.Web/Harvest.Web.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Publish Build Artifacts for master branch builds'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'